version: '3'

services:
  dataphoria.web.api.core:
    image: dataphoriawebapicore
    build:
      context: ../../
      dockerfile: Dataphoria/Dataphoria.Web.API.Core/Dockerfile
    volumes:
      - ./Instances:/usr/share/Alphora/Dataphor/Instances
      - ../../Libraries:/usr/share/Alphora/Dataphor/Libraries
      - ../../../medig/Application:/usr/share/Alphora/Application/Libraries

  db:
    image: postgres:alpine
    restart: always