version: '3'

services:
  dataphoria.web.api.core:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  db:
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "5432"
