version: '3.4'

services:
  dataphoria.web.api:
    image: dataphoriawebapi

    volumes:
      - ../../Dataphor/D4Runner/bin/Release/netcoreapp2.0/publish:/usr/share/Alphora/D4Runner
      - ./Dataphor:/usr/share/Alphora/Dataphor
      - ../../Libraries:/usr/share/Alphora/Libraries